module.exports = {
  absoluteUrl: /https?:\/\//,
  bitmap: /\.(gif|jpg|png)$/i,
  blacklist: /(node_modules|\.jus-cache\.json|redirects\.json)/,
  dataFile: /\.(json|yml|yaml)$/i,
  image: /\.(gif|jpg|png|svg)$/i,
  index: /\/index$/,
  jpg: /\.(jpg)$/i,
  json: /\.(json)$/i,
  markdown: /\.(md|markdown)$/i,
  nested: /\/\w+\//,
  page: /\.(md|markdown|handlebars|hbs|html)$/i,
  protocolRelativeUrl: /^\/\//,
  sass: /\.(sass)$/i,
  scss: /\.(scss)$/i,
  stylus: /\.(styl)$/i,
  script: /\.(js|coffee|es|es6)$/i,
  stylesheet: /\.(css|sass|scss|styl)$/i,
  yml: /\.(yml|yaml)$/i,
}
