module.exports = {
  page: /\.(md|markdown|handlebars|hbs|html)$/i,
  stylesheet: /\.(css|styl|sass|scss)$/i,
  script: /\.(js|coffee|es|es6)$/i,
  image: /\.(gif|jpg|png|svg)$/i,
  dataFile: /\.(json|yml|yaml)$/i,
  json: /\.(json)$/i,
  yml: /\.(yml|yaml)$/i,
  markdown: /\.(md|markdown)$/i,
  bitmap: /\.(gif|jpg|png)$/i,
  jpg: /\.(jpg)$/i,
  nested: /\/\w+\//,
  protocolRelativeUrl: /^\/\//,
  absoluteUrl: /https?:\/\//,
  index: /\/index$/,
  blacklist: /(node_modules|\.jus-cache\.json|redirects\.json)/,
}
