module.exports = {
  bitmap: /\.(gif|jpg|png)$/i,
  blacklist: /(\.git|node_modules|redirects\.json)/,
  datafile: /\.(json|yml|yaml)$/i,
  image: /\.(gif|jpg|png|svg)$/i,
  index: /\/index$/,
  jpg: /\.(jpg)$/i,
  json: /\.(json)$/i,
  layout: /^layout.*\.(html|hbs|handlebars|markdown|md)$/i,
  markdown: /\.(md|markdown)$/i,
  nested: /\/\w+\//,
  page: /^(?!layout).*\.*(md|markdown|handlebars|hbs|html)$/i,
  sass: /\.(sass)$/i,
  scss: /\.(scss)$/i,
  stylus: /\.(styl)$/i,
  script: /\.(js|jsx|es|es6)$/i,
  stylesheet: /\.(css|sass|scss|styl)$/i,
  yml: /\.(yml|yaml)$/i,
}
